name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v16
      - run: nix-build --arg cmakeFlags '["-DGROWT_BUILD_ALL_THIRD_PARTIES=ON"]'